name: Update R

on:
  schedule:
    - cron: '*/30 * * * *'  # This will run the workflow every 5 minutes.
  # push:
  #   branches: 
  #     - main  # This will also run when there are changes pushed to the main branch.
  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 2: Install required R packages
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            inegiR
            siebanxicor
            fredr

      # Step 3: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 4: Run all R scripts in the 'R' folder
      - name: Import data
        run: |
          # Loop through all .R files in the R folder and run them
          for file in scripts/r/*.R; do
            Rscript $file
          done

      # Step 5: Commit and push the updated data
      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add 'scripts/data/*.csv'  # Add all CSV files from the specific folder
          git commit -m "Update data" || echo "No changes to commit"
          git push

